[patch."https://github.com/okx/reth"]
reth = { path = "RETH_PATH_PLACEHOLDER/bin/reth" }
reth-chainspec = { path = "RETH_PATH_PLACEHOLDER/crates/chainspec" }
reth-chain-state = { path = "RETH_PATH_PLACEHOLDER/crates/chain-state" }
reth-cli = { path = "RETH_PATH_PLACEHOLDER/crates/cli/cli" }
reth-cli-commands = { path = "RETH_PATH_PLACEHOLDER/crates/cli/commands" }
reth-cli-util = { path = "RETH_PATH_PLACEHOLDER/crates/cli/util" }
reth-db = { path = "RETH_PATH_PLACEHOLDER/crates/storage/db" }
reth-errors = { path = "RETH_PATH_PLACEHOLDER/crates/errors" }
reth-ethereum-forks = { path = "RETH_PATH_PLACEHOLDER/crates/ethereum/hardforks" }
reth-evm = { path = "RETH_PATH_PLACEHOLDER/crates/evm/evm" }
reth-execution-types = { path = "RETH_PATH_PLACEHOLDER/crates/evm/execution-types" }
reth-exex = { path = "RETH_PATH_PLACEHOLDER/crates/exex/exex" }
reth-node-api = { path = "RETH_PATH_PLACEHOLDER/crates/node/api" }
reth-node-builder = { path = "RETH_PATH_PLACEHOLDER/crates/node/builder" }
reth-node-core = { path = "RETH_PATH_PLACEHOLDER/crates/node/core" }
reth-node-types = { path = "RETH_PATH_PLACEHOLDER/crates/node/types" }
reth-optimism-chainspec = { path = "RETH_PATH_PLACEHOLDER/crates/optimism/chainspec" }
reth-optimism-cli = { path = "RETH_PATH_PLACEHOLDER/crates/optimism/cli" }
reth-optimism-consensus = { path = "RETH_PATH_PLACEHOLDER/crates/optimism/consensus" }
reth-optimism-evm = { path = "RETH_PATH_PLACEHOLDER/crates/optimism/evm" }
reth-optimism-forks = { path = "RETH_PATH_PLACEHOLDER/crates/optimism/hardforks" }
reth-optimism-node = { path = "RETH_PATH_PLACEHOLDER/crates/optimism/node" }
reth-optimism-primitives = { path = "RETH_PATH_PLACEHOLDER/crates/optimism/primitives" }
reth-optimism-rpc = { path = "RETH_PATH_PLACEHOLDER/crates/optimism/rpc" }
reth-optimism-txpool = { path = "RETH_PATH_PLACEHOLDER/crates/optimism/txpool" }
reth-primitives = { path = "RETH_PATH_PLACEHOLDER/crates/primitives" }
reth-primitives-traits = { path = "RETH_PATH_PLACEHOLDER/crates/primitives-traits" }
reth-provider = { path = "RETH_PATH_PLACEHOLDER/crates/storage/provider" }
reth-revm = { path = "RETH_PATH_PLACEHOLDER/crates/revm" }
reth-rpc = { path = "RETH_PATH_PLACEHOLDER/crates/rpc/rpc" }
reth-rpc-convert = { path = "RETH_PATH_PLACEHOLDER/crates/rpc/rpc-convert" }
reth-rpc-eth-api = { path = "RETH_PATH_PLACEHOLDER/crates/rpc/rpc-eth-api" }
reth-storage-api = { path = "RETH_PATH_PLACEHOLDER/crates/storage/storage-api" }
reth-tracing = { path = "RETH_PATH_PLACEHOLDER/crates/tracing" }
reth-transaction-pool = { path = "RETH_PATH_PLACEHOLDER/crates/transaction-pool" }
