[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
homepage = "https://github.com/okx/xlayer-reth.git"
repository = "https://github.com/okx/xlayer-reth.git"

# ==============================================================================
# Workspace Configuration
# ==============================================================================

[workspace]
resolver = "2"
members = [
    "crates/node",
    "crates/tests",
    "crates/innertx",
    "crates/chainspec",
]
default-members = ["crates/node"]

[workspace.lints]

# ==============================================================================
# Build Profiles
# ==============================================================================

# Mimics reth release profile
[profile.release]
opt-level = 3
lto = "thin"
debug = "none"
strip = "symbols"
panic = "unwind"
codegen-units = 16

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1

# ==============================================================================
# Workspace Dependencies
# ==============================================================================

[workspace.dependencies]

# ------------------------------------------------------------------------------
# Internal Dependencies
# ------------------------------------------------------------------------------

xlayer-reth-node = { path = "crates/node" }
xlayer-innertx = { path = "crates/innertx" }
xlayer-chainspec = { path = "crates/chainspec" }
xlayer-rpc = { path = "crates/rpc" }

# ------------------------------------------------------------------------------
# Reth Dependencies (points to our fork)
# ------------------------------------------------------------------------------
reth = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-optimism-node = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-optimism-cli = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-primitives = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-rpc-eth-api = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-optimism-primitives = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-rpc-convert = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-optimism-rpc = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-optimism-evm = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-optimism-chainspec = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-provider = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-tracing = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-primitives-traits = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-evm = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-cli = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-cli-util = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-exex = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-db = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-revm = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-storage-api = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-rpc = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-node-api = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-node-builder = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-node-core = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-node-types = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-chainspec = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-optimism-forks = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-ethereum-forks = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-optimism-txpool = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-transaction-pool = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-execution-types = { git = "https://github.com/okx/reth", branch = "upstream/dev" }
reth-chain-state = { git = "https://github.com/okx/reth", branch = "upstream/dev" }

# ------------------------------------------------------------------------------
# Revm Dependencies (follows upstream reth)
# ------------------------------------------------------------------------------
revm = { version = "31.0.2", default-features = false }
revm-context-interface = { version = "12.0.1", default-features = false }
revm-database = { version = "9.0.5", default-features = false }

# ------------------------------------------------------------------------------
# Alloy Dependencies
# ------------------------------------------------------------------------------
alloy-primitives = { version = "1.4.1", default-features = false, features = [
    "map-foldhash",
] }
alloy-eips = { version = "1.0.41", default-features = false }
alloy-genesis = { version = "1.0.41", default-features = false }
alloy-chains = { version = "0.2.20", default-features = false }
alloy-rpc-types-engine = { version = "1.0.41", default-features = false }
alloy-rpc-types-eth = { version = "1.0.41" }
alloy-consensus = { version = "1.0.41" }
alloy-provider = { version = "1.0.41" }
alloy-sol-types = { version = "1.4.1", default-features = false }
alloy-network = { version = "1.1.0", default-features = false }
alloy-rlp = { version = "0.3.10", default-features = false, features = [
    "core-net",
] }
alloy-signer = { version = "1.1.0", default-features = false }
alloy-signer-local = { version = "1.1.0", default-features = false }
alloy-evm = { version = "0.23.0", default-features = false }
alloy-json-rpc = { version = "1.1.0" }
alloy-rpc-client = { version = "1.1.0" }
alloy-transport-http = { version = "1.1.0" }

# op-alloy
op-alloy-rpc-types = { version = "0.22.0", default-features = false }
op-alloy-rpc-types-engine = { version = "0.22.0", default-features = false }
op-alloy-rpc-jsonrpsee = { version = "0.22.0", default-features = false }
op-alloy-network = { version = "0.22.0", default-features = false }
op-alloy-consensus = { version = "0.22.0", default-features = false }

# ------------------------------------------------------------------------------
# Support Dependencies
# ------------------------------------------------------------------------------
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = "0.1.11"
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }

# async
futures = "0.3"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "stream"] }

# rpc
jsonrpsee = "0.26.0"

# misc
clap = { version = "4.4.3" }
tracing = { version = "0.1.41" }
serde = "1"
serde_json = "1.0"
url = "2.5"
metrics = "0.24.1"
metrics-derive = "0.1"
itertools = "0.14"
eyre = { version = "0.6.12" }
uuid = { version = "1.6.1", features = ["serde", "v5", "v4"] }
time = { version = "0.3.36", features = ["macros", "formatting", "parsing"] }
chrono = "0.4.41"
once_cell = "1.19"
tempfile = "3.20"
derive_more = { version = "2", default-features = false, features = ["full"] }
