[package]
name = "xlayer-reth-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "XLayer Reth Tools - Import and Export utilities"

[lints]
workspace = true

[[bin]]
name = "xlayer-reth-tools"
path = "main.rs"

[dependencies]
# internal
xlayer-chainspec.workspace = true
xlayer-version.workspace = true

# reth
reth-optimism-node.workspace = true
reth-optimism-evm.workspace = true
reth-optimism-chainspec.workspace = true
reth-cli.workspace = true
reth-cli-commands.workspace = true
reth-cli-util.workspace = true
reth-optimism-consensus.workspace = true
reth-tracing.workspace = true
reth-node-core.workspace = true
reth-chainspec.workspace = true
reth-provider.workspace = true
reth-storage-api.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-rlp.workspace = true

# tokio
tokio.workspace = true

# misc
clap.workspace = true
tracing.workspace = true
eyre.workspace = true
rayon = "1.10"
flate2 = "1.0"
ctrlc = "3.4"

[features]
default = []
jemalloc = ["reth-cli-util/jemalloc"]
